App/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain.Models;
using App.DAL;
using App.Enums;
using Microsoft.AspNet.Identity;

namespace App.Controllers
{
    public class CityEventArgs : EventArgs
    {
        public readonly City After;
        public readonly CrudEventEnumStatus Status;

        public CityEventArgs(City after, CrudEventEnumStatus status)
        {
            this.After = after;
            this.Status = status;
        }
    }

    public class CityController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public static event EventHandler<CityEventArgs> AfterCall;

        protected virtual void OnCrudOperation(CityEventArgs e)
        {
            if (AfterCall != null)
            {
                AfterCall(this, e);
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            ViewBag.Id = id;
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(City city)
        {
            if (ModelState.IsValid)
            {
                db.Cities.Add(city);

                db.SaveChanges(User.Identity.GetUserName());
                
                OnCrudOperation(new CityEventArgs(city, CrudEventEnumStatus.Create));

                if (!string.IsNullOrWhiteSpace(Request.QueryString["createNext"]))
                {
                    if (Request.QueryString["createNext"] == "true")
                    {
                        TempData["Created"] = true;
                        TempData["Alert"] = "Berhasil menambahkan City";
                        TempData["AlertClass"] = "success";

                        return RedirectToAction("Create");
                    }
                }

                return RedirectToAction("Details", new { id = city.Id});
            }

            TempData["Alert"] = "Gagal menambahkan City. Harap periksa kembali data yang anda input.";
            TempData["AlertClass"] = "danger";

            return View(city);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            ViewBag.Id = id;

            if (city == null)
            {
                return HttpNotFound();
            }

            return View(city);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(City city)
        {
            if (ModelState.IsValid)
            {
                db.Entry(city).State = EntityState.Modified;

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new CityEventArgs(city, CrudEventEnumStatus.Update));

                TempData["Alert"] = "Berhasil menyimpan perubahan City";
                TempData["AlertClass"] = "success";

                return RedirectToAction("Details", new { id = city.Id});
            }
            ViewBag.Id = city.Id;

            TempData["Alert"] = "Gagal melakukan perubahan City. Harap periksa kembali data yang anda masukkan.";
            TempData["AlertClass"] = "danger";

            return View(city);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            City city = db.Cities.Find(id);
            ViewBag.Id = id;

            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            City city = db.Cities.Find(id);
            ViewBag.Id = id;
            db.Cities.Remove(city);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new CityEventArgs(city, CrudEventEnumStatus.Delete));
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App/Controllers/DerekController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain.Models;
using App.DAL;
using App.Enums;
using Microsoft.AspNet.Identity;

namespace App.Controllers
{
    public class DerekEventArgs : EventArgs
    {
        public readonly Derek After;
        public readonly CrudEventEnumStatus Status;

        public DerekEventArgs(Derek after, CrudEventEnumStatus status)
        {
            this.After = after;
            this.Status = status;
        }
    }

    public class DerekController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public static event EventHandler<DerekEventArgs> AfterCall;

        protected virtual void OnCrudOperation(DerekEventArgs e)
        {
            if (AfterCall != null)
            {
                AfterCall(this, e);
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Derek derek = db.Dereks.Find(id);
            ViewBag.Id = id;
            if (derek == null)
            {
                return HttpNotFound();
            }
            return View(derek);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Derek derek)
        {
            if (ModelState.IsValid)
            {
                db.Dereks.Add(derek);

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new DerekEventArgs(derek, CrudEventEnumStatus.Create));

                if (!string.IsNullOrWhiteSpace(Request.QueryString["createNext"]))
                {
                    if (Request.QueryString["createNext"] == "true")
                    {
                        TempData["Created"] = true;
                        TempData["Alert"] = "Berhasil menambahkan Derek";
                        TempData["AlertClass"] = "success";

                        return RedirectToAction("Create");
                    }
                }

                return RedirectToAction("Details", new { id = derek.Id});
            }

            TempData["Alert"] = "Gagal menambahkan Derek. Harap periksa kembali data yang anda input.";
            TempData["AlertClass"] = "danger";

            return View(derek);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Derek derek = db.Dereks.Find(id);
            ViewBag.Id = id;

            if (derek == null)
            {
                return HttpNotFound();
            }

            return View(derek);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Derek derek)
        {
            if (ModelState.IsValid)
            {
                db.Entry(derek).State = EntityState.Modified;

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new DerekEventArgs(derek, CrudEventEnumStatus.Update));

                TempData["Alert"] = "Berhasil menyimpan perubahan Derek";
                TempData["AlertClass"] = "success";

                return RedirectToAction("Details", new { id = derek.Id});
            }
            ViewBag.Id = derek.Id;

            TempData["Alert"] = "Gagal melakukan perubahan Derek. Harap periksa kembali data yang anda masukkan.";
            TempData["AlertClass"] = "danger";

            return View(derek);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Derek derek = db.Dereks.Find(id);
            ViewBag.Id = id;

            if (derek == null)
            {
                return HttpNotFound();
            }
            return View(derek);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Derek derek = db.Dereks.Find(id);
            ViewBag.Id = id;
            db.Dereks.Remove(derek);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new DerekEventArgs(derek, CrudEventEnumStatus.Delete));
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App/Controllers/KerjaDerekController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain.Models;
using App.DAL;
using App.Enums;
using Microsoft.AspNet.Identity;

namespace App.Controllers
{
    public class KerjaDerekEventArgs : EventArgs
    {
        public readonly KerjaDerek After;
        public readonly CrudEventEnumStatus Status;

        public KerjaDerekEventArgs(KerjaDerek after, CrudEventEnumStatus status)
        {
            this.After = after;
            this.Status = status;
        }
    }

    public class KerjaDerekController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public static event EventHandler<KerjaDerekEventArgs> AfterCall;

        protected virtual void OnCrudOperation(KerjaDerekEventArgs e)
        {
            if (AfterCall != null)
            {
                AfterCall(this, e);
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KerjaDerek kerjaDerek = db.KerjaDereks.Find(id);
            ViewBag.Id = id;
            if (kerjaDerek == null)
            {
                return HttpNotFound();
            }
            return View(kerjaDerek);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(KerjaDerek kerjaDerek)
        {
            if (ModelState.IsValid)
            {
                db.KerjaDereks.Add(kerjaDerek);

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new KerjaDerekEventArgs(kerjaDerek, CrudEventEnumStatus.Create));

                if (!string.IsNullOrWhiteSpace(Request.QueryString["createNext"]))
                {
                    if (Request.QueryString["createNext"] == "true")
                    {
                        TempData["Created"] = true;
                        TempData["Alert"] = "Berhasil menambahkan KerjaDerek";
                        TempData["AlertClass"] = "success";

                        return RedirectToAction("Create");
                    }
                }

                return RedirectToAction("Details", new { id = kerjaDerek.Id});
            }

            TempData["Alert"] = "Gagal menambahkan KerjaDerek. Harap periksa kembali data yang anda input.";
            TempData["AlertClass"] = "danger";

            return View(kerjaDerek);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KerjaDerek kerjaDerek = db.KerjaDereks.Find(id);
            ViewBag.Id = id;

            if (kerjaDerek == null)
            {
                return HttpNotFound();
            }

            return View(kerjaDerek);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(KerjaDerek kerjaDerek)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kerjaDerek).State = EntityState.Modified;

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new KerjaDerekEventArgs(kerjaDerek, CrudEventEnumStatus.Update));

                TempData["Alert"] = "Berhasil menyimpan perubahan KerjaDerek";
                TempData["AlertClass"] = "success";

                return RedirectToAction("Details", new { id = kerjaDerek.Id});
            }
            ViewBag.Id = kerjaDerek.Id;

            TempData["Alert"] = "Gagal melakukan perubahan KerjaDerek. Harap periksa kembali data yang anda masukkan.";
            TempData["AlertClass"] = "danger";

            return View(kerjaDerek);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            KerjaDerek kerjaDerek = db.KerjaDereks.Find(id);
            ViewBag.Id = id;

            if (kerjaDerek == null)
            {
                return HttpNotFound();
            }
            return View(kerjaDerek);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            KerjaDerek kerjaDerek = db.KerjaDereks.Find(id);
            ViewBag.Id = id;
            db.KerjaDereks.Remove(kerjaDerek);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new KerjaDerekEventArgs(kerjaDerek, CrudEventEnumStatus.Delete));
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App/Views/Derek/Details.cshtml
@model Domain.Models.Derek

@{
    ViewBag.Title = "Details";

    var webApiUrl = System.Configuration.ConfigurationManager.AppSettings["webApiUrl"];
}

<div class="panel">
    <div class="panel-header border-bottom">
        <h2>
            <span class="fa fa-info-circle"></span> <strong>Derek - Details</strong>
        </h2>
    </div>
    <div class="panel-content">
        <dl class="dl-horizontal">
                    <dt>
                @Html.DisplayNameFor(model => model.City)
            </dt>

            <dd>
                <a href="@Url.Action("Details", "City", new { id = Model.City.Id })" >@Model.City.Name</a>
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.KerjaDerek)
            </dt>

            <dd>
                <a href="@Url.Action("Details", "KerjaDerek", new { id = Model.KerjaDerek.Id })" >@Model.KerjaDerek.Name</a>
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.PemegangPolis)
            </dt>

            <dd>
                <a href="@Url.Action("Details", "PemegangPolis", new { id = Model.PemegangPolis.Id })" >@Model.PemegangPolis.OwnerId</a>
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.Telephone)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Telephone)
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.EventDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EventDate)
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.EventTime)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EventTime)
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.Location)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Location)
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedAt)
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.LastUpdateTime)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastUpdateTime)
            </dd>
            </dl>
            <div id="tabstrip">
            <ul>
                    <li class="k-state-active">
                    Logs
                </li>
                </ul>
                <div id="grid-logs"></div>
            </div>
        <div style="height: 20px;"></div>
        </div>
    <div class="panel-footer">
        <p class="pull-right">
            @Html.ActionLink("Edit", "Edit", new { id = ViewBag.Id }) |
            @Html.ActionLink("Derek List", "Index")
            @if (Request.UrlReferrer != null)
            {
                @: | <a class="bottomNav" onclick="history.go(-1); return false;" href="#">Back</a><br />
            }
        </p>
        <div class="clearfix"></div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function() {
            $("#tabstrip").kendoTabStrip({
                animation:  {
                    open: {
                        effects: "fadeIn"
                    }
                }
            });
        });
        var dsLogs = new kendo.data.DataSource({
            type: "json",
            transport: {
                read: {
                    url: "@(webApiUrl)logs/Dereks/@ViewBag.Id",
                    dataType: "json",
                    contentType: "application/json"
                },
                parameterMap: function(options, operation) {
                    if (operation === "destroy") {
                        return null;
                    } else if (operation !== "read" && options.models) {
                        return { models: kendo.stringify(options.models) };
                    } else {
                        return "q=" + JSON.stringify(options);
                    }
                }
            },
            schema: {
                data: "Data",
                total: "Total",
                model: {
                    id: 'Id',
                    fields: {
                        EventDateUTC: {
                            type: "date"
                        }
                    }
                }
            },
            serverFiltering: true,
            serverPaging: true,
            serverSorting: true,
            pageSize: 10
        });

        $("#grid-logs").kendoGrid({
            dataSource: dsLogs,
            sortable: true,
            filterable: {
                mode: "row"
            },
            pageable: {
                refresh: true,
                pageSizes: true,
                buttonCount: 5
            },
            groupable: true,
            columns: [
                {
                    field: "EventType",
                    title: "Type"
                },
                {
                    field: "EventDateUTC",
                    title: "Change Date",
                    format: "{0: yyyy-MM-dd HH:mm:ss}"
                },
                {
                    field: "ColumnName",
                    title: "Column"
                },
                {
                    field: "OriginalValue",
                    title: "Original"
                },
                {
                    field: "NewValue",
                    title: "New"
                },
                {
                    field: "UserName",
                    title: "By"
                }
            ]
        });
    </script>
}