App/Controllers/PemegangPolisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain.Models;
using App.DAL;
using App.Enums;
using Microsoft.AspNet.Identity;

namespace App.Controllers
{
    public class PemegangPolisEventArgs : EventArgs
    {
        public readonly PemegangPolis After;
        public readonly CrudEventEnumStatus Status;

        public PemegangPolisEventArgs(PemegangPolis after, CrudEventEnumStatus status)
        {
            this.After = after;
            this.Status = status;
        }
    }

    public class PemegangPolisController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public static event EventHandler<PemegangPolisEventArgs> AfterCall;

        protected virtual void OnCrudOperation(PemegangPolisEventArgs e)
        {
            if (AfterCall != null)
            {
                AfterCall(this, e);
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PemegangPolis pemegangPolis = db.PemegangPolis.Find(id);
            ViewBag.Id = id;
            if (pemegangPolis == null)
            {
                return HttpNotFound();
            }
            return View(pemegangPolis);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PemegangPolis pemegangPolis)
        {
            /// NOTES: IF (admin) then show user list from ASP.USER
            /// IF USER then cannot create OR 
            /// in an alternative case, User List become his/her own ID (shown as USERNAME/EMAIL)
            /// ---------not done
            /// may be applied in EDIT too
            /// ---------
            /// for a time being this actionresult will use his/her own ID (unshown)
            if (ModelState.IsValid)
            {
                pemegangPolis.OwnerId = User.Identity.GetUserId();

                db.PemegangPolis.Add(pemegangPolis);
                
                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new PemegangPolisEventArgs(pemegangPolis, CrudEventEnumStatus.Create));

                if (!string.IsNullOrWhiteSpace(Request.QueryString["createNext"]))
                {
                    if (Request.QueryString["createNext"] == "true")
                    {
                        TempData["Created"] = true;
                        TempData["Alert"] = "Berhasil menambahkan PemegangPolis";
                        TempData["AlertClass"] = "success";

                        return RedirectToAction("Create");
                    }
                }

                return RedirectToAction("Details", new { id = pemegangPolis.Id});
            }

            TempData["Alert"] = "Gagal menambahkan PemegangPolis. Harap periksa kembali data yang anda input.";
            TempData["AlertClass"] = "danger";

            return View(pemegangPolis);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PemegangPolis pemegangPolis = db.PemegangPolis.Find(id);
            ViewBag.Id = id;

            if (pemegangPolis == null)
            {
                return HttpNotFound();
            }

            return View(pemegangPolis);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PemegangPolis pemegangPolis)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pemegangPolis).State = EntityState.Modified;

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new PemegangPolisEventArgs(pemegangPolis, CrudEventEnumStatus.Update));

                TempData["Alert"] = "Berhasil menyimpan perubahan PemegangPolis";
                TempData["AlertClass"] = "success";

                return RedirectToAction("Details", new { id = pemegangPolis.Id});
            }
            ViewBag.Id = pemegangPolis.Id;

            TempData["Alert"] = "Gagal melakukan perubahan PemegangPolis. Harap periksa kembali data yang anda masukkan.";
            TempData["AlertClass"] = "danger";

            return View(pemegangPolis);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            PemegangPolis pemegangPolis = db.PemegangPolis.Find(id);
            ViewBag.Id = id;

            if (pemegangPolis == null)
            {
                return HttpNotFound();
            }
            return View(pemegangPolis);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PemegangPolis pemegangPolis = db.PemegangPolis.Find(id);
            ViewBag.Id = id;
            db.PemegangPolis.Remove(pemegangPolis);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new PemegangPolisEventArgs(pemegangPolis, CrudEventEnumStatus.Delete));
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App/Controllers/WebApi/PemegangPolisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Linq.Dynamic;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Kendo.DynamicLinq;
using Newtonsoft.Json;
using Domain.Models;
using App.DAL;
using App.Enums;
using App.Helper;
using Domain.Models.ViewModels;
using Microsoft.AspNet.Identity;

namespace App.Controllers.WebApi
{
    public class PemegangPolisControllerEventArgs : EventArgs
    {
        public readonly PemegangPolis After;
        public readonly CrudEventEnumStatus Status;

        public PemegangPolisControllerEventArgs(PemegangPolis after, CrudEventEnumStatus status)
        {
            this.After = after;
            this.Status = status;
        }
    }

    public class PemegangPolisController : ApiController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public static event EventHandler<PemegangPolisControllerEventArgs> AfterCall;

        protected virtual void OnCrudOperation(PemegangPolisControllerEventArgs e)
        {
            if (AfterCall != null)
            {
                AfterCall(this, e);
            }
        }

        // GET: api/PemegangPolis
        public DataSourceResult GetPemegangPolis(HttpRequestMessage requestMessage)
        {
            DataSourceRequest request =
                JsonConvert.DeserializeObject<DataSourceRequest>(requestMessage.RequestUri.ParseQueryString().GetValues("q")[0]);

            if (request.Filter != null && !request.Filter.Filters.Any())
            {
                request.Filter = null;
            }
            else
            {
                request.Filter.ToCustomExpression();
            }

            var result = db.PemegangPolis.Include(x => x.Owner).AsQueryable();

            return result
                .OrderBy(x => x.Id)
                .Project()
                .To<PemegangPolisViewModel>()
                .ToDataSourceResult(request.Take, request.Skip, request.Sort, request.Filter);
        }

        // GET: api/PemegangPolis/5
        [ResponseType(typeof(PemegangPolisViewModel))]
        public IHttpActionResult GetPemegangPolis(int id)
        {
            PemegangPolis pemegangPolis = db.PemegangPolis.Find(id);
            if (pemegangPolis == null)
            {
                return NotFound();
            }

            return Ok(Mapper.Map<PemegangPolis, PemegangPolisViewModel>(pemegangPolis));
        }

        // PUT: api/PemegangPolis/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutPemegangPolis(int id, PemegangPolisViewModel pemegangPolis)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != pemegangPolis.Id)
            {
                return BadRequest();
            }

            var temppemegangPolis = pemegangPolis.ToEntity();

            db.Entry(temppemegangPolis).State = EntityState.Modified;

            try
            {
                db.SaveChanges(User.Identity.GetUserName());
                OnCrudOperation(new PemegangPolisControllerEventArgs(temppemegangPolis, CrudEventEnumStatus.Update));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PemegangPolisExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/PemegangPolis
        [ResponseType(typeof(PemegangPolisViewModel))]
        public IHttpActionResult PostPemegangPolis(PemegangPolisViewModel pemegangPolis)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var temppemegangPolis = pemegangPolis.ToEntity();

            db.PemegangPolis.Add(temppemegangPolis);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new PemegangPolisControllerEventArgs(temppemegangPolis, CrudEventEnumStatus.Create));

            return CreatedAtRoute("DefaultApi", new { id = pemegangPolis.Id }, 
                    Mapper.Map<PemegangPolis, PemegangPolisViewModel>(temppemegangPolis));
        }

        // DELETE: api/PemegangPolis/5
        [ResponseType(typeof(PemegangPolisViewModel))]
        public IHttpActionResult DeletePemegangPolis(int id)
        {
            PemegangPolis pemegangPolis = db.PemegangPolis.Find(id);
            if (pemegangPolis == null)
            {
                return NotFound();
            }

            db.PemegangPolis.Remove(pemegangPolis);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new PemegangPolisControllerEventArgs(pemegangPolis, CrudEventEnumStatus.Delete));

            return Ok(Mapper.Map<PemegangPolis, PemegangPolisViewModel>(pemegangPolis));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool PemegangPolisExists(int id)
        {
            return db.PemegangPolis.Count(e => e.Id == id) > 0;
        }
    }
}

App/Views/PemegangPolis/Create.cshtml
@model Domain.Models.PemegangPolis

@{
    ViewBag.Title = "Create";
    var webApiUrl = System.Configuration.ConfigurationManager.AppSettings["webApiUrl"];
}

<div class="panel">
    <div class="panel-header border-bottom">
        <h2>
            <span class="fa fa-plus-circle"></span> <strong>PemegangPolis - Create</strong>
        </h2>
    </div>
    <div class="panel-content">
    @using (Html.BeginForm("Create", "PemegangPolis", FormMethod.Post, new { @id = "formCreate" })) 
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @*<div class="form-group">
                    @Html.LabelFor(model => model.OwnerId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                            @Html.DropDownList("OwnerId", new SelectList(new List<string>()), htmlAttributes: new { @class = "form-control kendo-dropdownlist", @id = "OwnerId" })
                                @Html.ValidationMessageFor(model => model.OwnerId, "", new { @class = "text-danger" })
                        </div>
            </div>*@

                <div class="form-group">
                    @Html.LabelFor(model => model.NomorPolis, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NomorPolis, new { @class = "form-control form-white" })
                            @Html.ValidationMessageFor(model => model.NomorPolis, "", new { @class = "text-danger" })
                        </div>
            </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NomorMesin, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NomorMesin, new { @class = "form-control form-white" })
                            @Html.ValidationMessageFor(model => model.NomorMesin, "", new { @class = "text-danger" })
                        </div>
            </div>

                <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="k-button" /> &nbsp; <button type="submit" value="true" name="createNext" class="k-button k-primary">Save and create next</button>
                </div>
            </div>
        </div>
    }
    </div>
    <div class="panel-footer">
        <p class="pull-right">
            @Html.ActionLink("PemegangPolis List", "Index")
            @if (Request.UrlReferrer != null)
            {
                @: | <a class="bottomNav" onclick="history.go(-1); return false;" href="#">Back</a><br/>
            }
        </p>
        <div class="clearfix"></div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $("#formCreate").validate({
            rules: {
                OwnerId: {
                },
                NomorPolis: {
                },
                NomorMesin: {
                },
            }
        });

        $(".kendo-dropdownlist").kendoDropDownList({
            filter: "contains"
        });

        $("button[name='createNext']").click(function (e) {
            var url = $("#formCreate").attr("action") + "?createNext=true";
            $("#formCreate").attr("action", url);
        });

        var dsOwnerId = new kendo.data.DataSource({
            type: "json",
            transport: {
                read: {
                    url: "@(webApiUrl)Owners",
                    dataType: "json",
                    contentType: "application/json",
                },
                parameterMap: function (options, operation) {
                    if (operation === "destroy") {
                        return null;
                    } else if (operation !== "read" && options.models) {
                        return { models: kendo.stringify(options.models) };
                    } else {
                        return "q=" + JSON.stringify(options);
                    }
                }
            },
            schema: {
                data: "Data",
                total: "Total",
                model: {
                    id: 'Id',
                    fields: {
                        
                    }
                }
            },
            serverFiltering: true,
            serverPaging: true,
            pageSize: 7
        });

        $("#OwnerId").kendoDropDownList({
            filter: "contains",
            dataSource: dsOwnerId,
            dataTextField: "Email",
            dataValueField: "Id",
        });

        $(".kendo-datetimepicker").kendoDateTimePicker({
            format: "yyyy-MM-dd HH:mm"
        });
    </script>
}

App/Views/PemegangPolis/Details.cshtml
@model Domain.Models.PemegangPolis

@{
    ViewBag.Title = "Details";

    var webApiUrl = System.Configuration.ConfigurationManager.AppSettings["webApiUrl"];
}

<div class="panel">
    <div class="panel-header border-bottom">
        <h2>
            <span class="fa fa-info-circle"></span> <strong>PemegangPolis - Details</strong>
        </h2>
    </div>
    <div class="panel-content">
        <dl class="dl-horizontal">
                    <dt>
                @Html.DisplayNameFor(model => model.Owner)
            </dt>

            <dd>
                @if (Model.OwnerId == null)
                {
                    <span class='text'>Anonymous</span>
                }
                else
                { <a href="@Url.Action("Details", "ApplicationUser", new { id = Model.Owner.Id })">@Model.Owner.Email</a> }
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.NomorPolis)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NomorPolis)
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.NomorMesin)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NomorMesin)
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedAt)
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.LastUpdateTime)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastUpdateTime)
            </dd>
            </dl>
            <div id="tabstrip">
            <ul>
                    <li class="k-state-active">
                    Logs
                </li>
                </ul>
                <div id="grid-logs"></div>
            </div>
        <div style="height: 20px;"></div>
        </div>
    <div class="panel-footer">
        <p class="pull-right">
            @Html.ActionLink("Edit", "Edit", new { id = ViewBag.Id }) |
            @Html.ActionLink("PemegangPolis List", "Index")
            @if (Request.UrlReferrer != null)
            {
                @: | <a class="bottomNav" onclick="history.go(-1); return false;" href="#">Back</a><br />
            }
        </p>
        <div class="clearfix"></div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function() {
            $("#tabstrip").kendoTabStrip({
                animation:  {
                    open: {
                        effects: "fadeIn"
                    }
                }
            });
        });
        var dsLogs = new kendo.data.DataSource({
            type: "json",
            transport: {
                read: {
                    url: "@(webApiUrl)logs/PemegangPolis/@ViewBag.Id",
                    dataType: "json",
                    contentType: "application/json"
                },
                parameterMap: function(options, operation) {
                    if (operation === "destroy") {
                        return null;
                    } else if (operation !== "read" && options.models) {
                        return { models: kendo.stringify(options.models) };
                    } else {
                        return "q=" + JSON.stringify(options);
                    }
                }
            },
            schema: {
                data: "Data",
                total: "Total",
                model: {
                    id: 'Id',
                    fields: {
                        EventDateUTC: {
                            type: "date"
                        }
                    }
                }
            },
            serverFiltering: true,
            serverPaging: true,
            serverSorting: true,
            pageSize: 10
        });

        $("#grid-logs").kendoGrid({
            dataSource: dsLogs,
            sortable: true,
            filterable: {
                mode: "row"
            },
            pageable: {
                refresh: true,
                pageSizes: true,
                buttonCount: 5
            },
            groupable: true,
            columns: [
                {
                    field: "EventType",
                    title: "Type"
                },
                {
                    field: "EventDateUTC",
                    title: "Change Date",
                    format: "{0: yyyy-MM-dd HH:mm:ss}"
                },
                {
                    field: "ColumnName",
                    title: "Column"
                },
                {
                    field: "OriginalValue",
                    title: "Original"
                },
                {
                    field: "NewValue",
                    title: "New"
                },
                {
                    field: "UserName",
                    title: "By"
                }
            ]
        });
    </script>
}

App/Views/PemegangPolis/Edit.cshtml
@model Domain.Models.PemegangPolis

@{
    ViewBag.Title = "Edit";

    var webApiUrl = System.Configuration.ConfigurationManager.AppSettings["webApiUrl"];
}
<div class="panel">
    <div class="panel-header border-bottom">
        <h2>
            <span class="fa fa-edit"></span> <strong>PemegangPolis - Edit</strong>
        </h2>
    </div>
    <div class="panel-content">
        @using (Html.BeginForm("Edit", "PemegangPolis", FormMethod.Post, new { @id = "formEdit" }))
        {
            @Html.AntiForgeryToken()
    
            <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.Id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.NomorPolis, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.NomorPolis, new { @class = "form-control form-white" })
                                        @Html.ValidationMessageFor(model => model.NomorPolis, "", new { @class = "text-danger" })
                                    </div>
                </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.NomorMesin, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.NomorMesin, new { @class = "form-control form-white" })
                                        @Html.ValidationMessageFor(model => model.NomorMesin, "", new { @class = "text-danger" })
                                    </div>
                </div>
                        
                        @Html.HiddenFor(model => model.CreatedAt)
                        @Html.HiddenFor(model => model.LastUpdateTime)
                        <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="k-button k-primary" />
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="panel-footer">
        <p class="pull-right">
            @Html.ActionLink("Details", "Details", new { id = ViewBag.Id }) |
            @Html.ActionLink("PemegangPolis List", "Index")
            @if (Request.UrlReferrer != null)
            {
                @: | <a class="bottomNav" onclick="history.go(-1); return false;" href="#">Back</a><br/>
            }
        </p>
        <div class="clearfix"></div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $("#formEdit").validate({
            rules: {
                OwnerId: {
                },
                NomorPolis: {
                },
                NomorMesin: {
                },
            }
        });
        var dsOwnerId = new kendo.data.DataSource({
            type: "json",
            transport: {
                read: {
                    url: "@(webApiUrl)Owners",
                    dataType: "json",
                    contentType: "application/json",
                },
                parameterMap: function (options, operation) {
                    if (operation === "destroy") {
                        return null;
                    } else if (operation !== "read" && options.models) {
                        return { models: kendo.stringify(options.models) };
                    } else {
                        return "q=" + JSON.stringify(options);
                    }
                }
            },
            schema: {
                data: "Data",
                total: "Total",
                model: {
                    id: 'Id',
                    fields: {
                        
                    }
                }
            }
        });

        $("#OwnerId").kendoDropDownList({
            filter: "contains",
            dataSource: dsOwnerId,
            dataTextField: "Email",
            dataValueField: "Id",
            value: "@Model.OwnerId"
        });

        $(".kendo-datetimepicker").kendoDateTimePicker({
            format: "yyyy-MM-dd HH:mm"
        });
    </script>
}